### PR TITLE
Standards cms

### PR DESCRIPTION
**Pull request by mgouzevi**
I modified a bit the Diagrams to adapt to the CMS standards we tend to use: "H" instead of "h" and c2 instead of c2t.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
Thanks! could you rename the files so that it overwrites the old ones ?

**Comment by mgouzevi** [comment]
Hi Olivier,

you mean remove "_CMS"? In that case I shall do it also for resonant and 
SM file.


Max

**Comment by OlivierBondu** [comment]
ping !

**Comment by OlivierBondu** [comment]
thanks!

**Pull request merged**
